### PR TITLE
added property to allow overlay to be hidden

### PR DESCRIPTION
**Pull request by marc-harry**

### CODE REVIEW

**Comment by GiampaLab** [comment]
Any test coverage we can add for the new functionality?

**Comment by ibrahimuylas** [comment]
Build looks failed. Could you please fix it?

**Comment by marc-harry** [comment]
@GiampaLab I've added test coverage for new functionality

**Comment by marc-harry** [comment]
@ibrahimuylas Build is passing but it is flagging NPM vulnerabilities during the build

**Review by ibrahimuylas — APPROVED** [review]

**Review by GiampaLab — APPROVED** [review]

**Review by sedainterxion — APPROVED** [review]

**Pull request merged**
